import { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState('en'); // 'en' or 'np'

    const translations = {
        en: {
            welcome: "Welcome back",
            todayWeather: "Today's Weather",
            feelsLike: "Feels like",
            rain: "Rain",
            wind: "Wind",
            aiCropDoctor: "AI Crop Doctor",
            scanAdvice: "Scan your crop for advice",
            takePhoto: "Take Photo or Upload",
            cropLeaf: "of your crop leaf",
            camera: "Camera",
            file: "File",
            marketPrices: "Market Prices",
            marketRates: "market rates",
            seeAll: "See All",
            home: "Home",
            jobs: "Jobs",
            alerts: "Alerts",
            profile: "Profile",
            menu: "Menu",
            cropCalculator: "Crop Calculator",
            selectCrop: "Select Crop",
            quantity: "Quantity",
            totalPrice: "Total Estimated Price",
            settings: "Settings",
            appPref: "App preferences",
            notifications: "Notifications",
            manageAlerts: "Manage alerts",
            language: "Language",
            chooseLang: "Choose app language",
            contactInfo: "Contact Information",
            farmSize: "Farm Size",
            mainCrops: "Main Crops",
            thisSeason: "This season",
            myJobs: "My Jobs Today",
            progress: "Progress",
            tasksRemaining: "tasks remaining",
            rice: "Rice",
            wheat: "Wheat",
            maize: "Maize",
            vegetables: "Vegetables",
            milk: "Milk",
            heavyRainTitle: "Heavy Rain Expected",
            heavyRainMsg: "Rain forecast for tomorrow. Cover your crops!",
            pestTitle: "Pest Warning",
            pestMsg: "Brown planthopper detected in Morang district",
            priceTitle: "Price Update",
            priceMsg: "Rice price increased by 5% in local market",
            stockTitle: "Stock Available",
            stockMsg: "Urea now available at Dharan Depot",
            taskReminder: "Task Reminder",
            taskMsg: "Don't forget: Spray pesticide tomorrow morning",
            waterRiceField: "Water rice field",
            checkPests: "Check for pests",
            checkCropHealth: "Check crop health",
            buyFertilizer: "Buy fertilizer",
            farmMeeting: "Farm meeting",
            newAlerts: "new alerts",
            ago: "ago",
            hours: "hours",
            yesterday: "Yesterday",
            tomorrowMorning: "Tomorrow morning",
            per: "per",
            stable: "Stable",
            sunny: "Sunny",
            cloudy: "Cloudy",
            rainy: "Rainy",
            dhangadhi: "Dhangadhi"
        },
        np: {
            welcome: "स्वागत छ",
            todayWeather: "आजको मौसम",
            feelsLike: "महसुस",
            rain: "वर्षा",
            wind: "हावा",
            aiCropDoctor: "एआई बाली डाक्टर",
            scanAdvice: "सल्लाहको लागि बाली स्क्यान गर्नुहोस्",
            takePhoto: "फोटो खिच्नुहोस् वा अपलोड गर्नुहोस्",
            cropLeaf: "तपाईंको बालीको पातको",
            camera: "क्यामेरा",
            file: "फाइल",
            marketPrices: "बजार मूल्यहरू",
            marketRates: "बजार दरहरू",
            seeAll: "सबै हेर्नुहोस्",
            home: "गृहपृष्ठ",
            jobs: "कामहरु",
            alerts: "सूचनाहरू",
            profile: "प्रोफाइल",
            menu: "मेनु",
            cropCalculator: "बाली क्याल्कुलेटर",
            selectCrop: "बाली छान्नुहोस्",
            quantity: "परिमाण",
            totalPrice: "कुल अनुमानित मूल्य",
            settings: "सेटिङहरू",
            appPref: "एप प्राथमिकताहरू",
            notifications: "सूचनाहरू",
            manageAlerts: "अलर्ट व्यवस्थापन",
            language: "भाषा",
            chooseLang: "भाषा छान्नुहोस्",
            contactInfo: "सम्पर्क जानकारी",
            farmSize: "खेतको आकार",
            mainCrops: "मुख्य बालीहरू",
            thisSeason: "यो सिजन",
            myJobs: "आजका मेरा कामहरू",
            progress: "प्रगति",
            tasksRemaining: "बाँकी कामहरू",
            rice: "धान",
            wheat: "गहुँ",
            maize: "मकै",
            vegetables: "तरकारी",
            milk: "दुध",
            heavyRainTitle: "भारी वर्षाको सम्भावना",
            heavyRainMsg: "भोलिको लागि वर्षाको पूर्वानुमान। आफ्नो बाली छोप्नुहोस्!",
            pestTitle: "कीराको चेतावनी",
            pestMsg: "मोरङ जिल्लामा खैरो फड्के कीरा देखा पर्यो",
            priceTitle: "मूल्य अपडेट",
            priceMsg: "स्थानीय बजारमा धानको मूल्य ५% ले बढ्यो",
            stockTitle: "स्टक उपलब्ध छ",
            stockMsg: "धरान डिपोमा अब युरिया उपलब्ध छ",
            taskReminder: "कामको सम्झना",
            taskMsg: "नबिर्सनुहोस्: भोलि बिहान कीटनाशक छर्कनुहोस्",
            waterRiceField: "धान खेतमा पानी हाल्ने",
            checkPests: "कीरा जाँच गर्ने",
            checkCropHealth: "बालीको स्वास्थ्य जाँच",
            buyFertilizer: "मल किन्न जाने",
            farmMeeting: "कृषि बैठक",
            newAlerts: "नयाँ सूचनाहरू",
            ago: "अघि",
            hours: "घण्टा",
            yesterday: "हिजो",
            tomorrowMorning: "भोलि बिहान",
            per: "प्रति",
            stable: "स्थिर",
            sunny: "घमाइलो",
            cloudy: "बादल",
            rainy: "वर्षा",
            dhangadhi: "धनगढी"
        }
    };

    const t = (key) => translations[language][key] || key;

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};
